server:
  port: 8280
spring:
  profiles:
    active: dev
  application:
    name: storage
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        query-passing: true
  rabbitmq:
    host: ${RABBIT_URL:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:admin}
    password: ${RABBIT_PASSWORD:admin}
  jackson:
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
app:
  file-dir: /var/lib/cloud-oj/