server:
  port: 8180
spring:
  profiles:
    active: dev
  application:
    name: core
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  main:
    allow-circular-references: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost:3306}/cloud_oj?allowMultiQueries=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    hikari:
      connection-timeout: 10000
      maximum-pool-size: ${DB_POOL_SIZE:10}
      max-lifetime: 30000
  jackson:
    default-property-inclusion: non_null
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        query-passing: true
        prefer-ip-address: ${USE_IP:false}
        ip-address: ${SERVICE_IP:${spring.cloud.client.ip-address}}
        health-check-critical-timeout: 5m
management:
  endpoint:
    health:
      show-details: ALWAYS
mybatis:
  configuration:
    map-underscore-to-camel-case: on
  mapper-locations: classpath:mybatis/mapper/*.xml