server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: gateway
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost:3306}/cloud_oj?serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    hikari:
      connection-timeout: 10000
      maximum-pool-size: ${DB_POOL_SIZE:10}
      max-lifetime: 30000
  jackson:
    default-property-inclusion: non_null
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=20m
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        query-passing: true
        prefer-ip-address: ${USE_IP:false}
        ip-address: ${SERVICE_IP:${spring.cloud.client.ip-address}}
        instance-id: ${spring.application.name}-${server.port}-${random.int}
        health-check-critical-timeout: 5m
    gateway:
      routes:
        - id: core
          uri: lb://core
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/core/**
        - id: judge
          uri: lb://judge
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/judge/**
        - id: auth
          uri: lb://gateway
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/auth/**
      discovery:
        locator:
          enabled: true
      observability:
        enabled: false
management:
  endpoint:
    health:
      show-details: always
mybatis:
  configuration:
    map-underscore-to-camel-case: on
  mapper-locations: classpath:mybatis/mapper/*.xml
app:
  token-valid-time: ${TOKEN_VALID_TIME:4}