server:
  port: 8380
spring:
  profiles:
    active: dev
  application:
    name: judge
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost:3306}/cloud_oj?allowMultiQueries=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  rabbitmq:
    host: ${RABBIT_URL:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:admin}
    password: ${RABBIT_PASSWORD:admin}
    listener:
      simple:
        acknowledge-mode: manual
  jackson:
    default-property-inclusion: non_null
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        query-passing: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
mybatis:
  configuration:
    map-underscore-to-camel-case: on
  mapper-locations: classpath:mybatis/mapper/*.xml