logging:
  level:
    root: info
    cloud.oj: info
app:
  code-dir: /tmp/code/
  file-dir: /var/lib/cloud-oj/
  auto-clean-solution: ${AUTO_CLEAN_SOLUTION:true}
  judge-pool-size: ${JUDGE_POOL_SIZE:0}