version: "3.7"
services:
  consul:
    image: consul:latest
    command:
      - "agent"
      - "-server"
      - "-ui"
      - "-bind=127.0.0.1"
      - "-retry-join=127.0.0.1"
      - "-bootstrap-expect=1"
      - "-client=0.0.0.0"
      - "-log-level=err"
    networks:
      - cloud-oj
    ports:
      - "8500:8500"
    volumes:
      - "consul:/consul/data"
  storage:
    image: cloud-oj-storage
    depends_on:
      - "consul"
      - "mariadb"
      - "rabbitmq"
    networks:
      - cloud-oj
    volumes:
      - "/var/lib/cloud-oj:/var/lib/cloud-oj"
    environment:
      JVM_OPTS: "-Xmx100m"
      CONSUL_HOST: "consul"
      RABBIT_URL: rabbitmq
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWD}
  gateway:
    image: cloud-oj-gateway
    depends_on:
      - "consul"
      - "mariadb"
      - "rabbitmq"
    networks:
      - cloud-oj
    environment:
      JVM_OPTS: "-Xmx200m"
      CONSUL_HOST: "consul"
      DB_HOST: "mariadb:3306"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWD}
      DB_POOL_SIZE: 5
      TOKEN_VALID_TIME: 4
  core:
    image: cloud-oj-core
    depends_on:
      - "consul"
      - "mariadb"
      - "rabbitmq"
    networks:
      - cloud-oj
    environment:
      JVM_OPTS: "-Xmx200m"
      CONSUL_HOST: "consul"
      DB_HOST: "mariadb:3306"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWD}
      DB_POOL_SIZE: 5
  judge:
    image: cloud-oj-judge
    privileged: true
    depends_on:
      - "consul"
      - "mariadb"
      - "rabbitmq"
    networks:
      - cloud-oj
    volumes:
      - "/var/lib/cloud-oj:/var/lib/cloud-oj"
    environment:
      JVM_OPTS: "-Xmx300m"
      CONSUL_HOST: "consul"
      DB_HOST: "mariadb:3306"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWD}
      DB_POOL_SIZE: 5
      RABBIT_URL: rabbitmq
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWD}
      JUDGE_POOL_SIZE: 0
  web:
    image: cloud-oj-web
    networks:
      - cloud-oj
    ports:
      - "80:80"
    environment:
      API_HOST: "gateway:8080"
  mariadb:
    image: mariadb:latest
    networks:
      - cloud-oj
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      - "mariadb:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWD}
      MARIADB_ROOT_HOST: "%"
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    hostname: rabbitmq
    networks:
      - cloud-oj
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWD}
    ports:
      - "15672:15672"
    volumes:
      - "rabbitmq:/var/lib/rabbitmq/mnesia"
networks:
  cloud-oj:
    driver: bridge
volumes:
  consul:
  mariadb:
  rabbitmq: